### ISSUE TITLE
CIS operator set up with nodeport without VXLAN for OpenShift

### ISSUE THREAD

**Issue by cnukwas** [mdditt2000/k8s-bigip-ctlr#1]
Hi,

Thanks for the documentation, it has certainly helped to understand CIS operator set up but we're missing few things as we're trying to use [Nodeport](https://clouddocs.f5.com/containers/latest/userguide/config-options.html#config-options) deployment without VXLAN set up. Would you mind outlining high level steps on the BIG-IP side to use the nodeport approach?

We have user id, BIG-IP partition created based on the [documentation](https://clouddocs.f5.com/containers/latest/userguide/openshift/), but getting lost after installing the operator and seeing errors with liveness and readyness probes after creating F5BigIpCtlr instance.

I see many different posts on this topic, so it's little confusing to follow since the documentation appears to be incomplete.

Thanks

**Comment by mdditt2000** [comment]
@cnukwas just saw your comment. I will create you NodePort deployment write-up plus video later this week. This will cover high level steps on the BIG-IP side etc. I am going to record this video and document OpenShift 4-8 using OVN-Kubernetes with CIS NodePort instead of the Hybrid-Overlay feature that i just documented. Please view that doc and watch the YouTube demo at https://github.com/mdditt2000/k8s-bigip-ctlr/blob/main/user_guides/openshift-4-8/standalone-ovn-k8s-hybrid/README.md

**Comment by mdditt2000** [comment]
@cnukwas please review the new document that i created for OpenShift where no VXLAN is required. You can use clusterIP or NodePort mode. I would recommend ClusterIP. Please let me know your thoughts 

https://github.com/mdditt2000/k8s-bigip-ctlr/tree/main/user_guides/ovn-kubernetes-standalone#readme

**Comment by mdditt2000** [comment]
Closing issue out
